/*
 * generated by Xtext
 */
package edu.vanderbilt.isis.chariot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DatatypesUiModule extends edu.vanderbilt.isis.chariot.ui.AbstractDatatypesUiModule {
	public DatatypesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
