/*
 * generated by Xtext
 */
package edu.vanderbilt.isis.chariot.ui.contentassist

import edu.vanderbilt.isis.chariot.ui.contentassist.AbstractChariotProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ChariotProposalProvider extends AbstractChariotProposalProvider {
}
