/*
 * generated by Xtext
 */
package edu.vanderbilt.isis.chariot;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DatatypesStandaloneSetup extends DatatypesStandaloneSetupGenerated{

	public static void doSetup() {
		new DatatypesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

