/*
 * generated by Xtext
 */
package edu.vanderbilt.isis.chariot.ui.contentassist

import edu.vanderbilt.isis.chariot.ui.contentassist.AbstractDatatypesProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DatatypesProposalProvider extends AbstractDatatypesProposalProvider {
}
