/*
 * generated by Xtext
 */
package edu.vanderbilt.isis.chariot.validation
import com.google.inject.Inject
import org.eclipse.xtext.validation.Check
import edu.vanderbilt.isis.chariot.datatypes.MessageElement
import edu.vanderbilt.isis.chariot.AllowableTypes
import static edu.vanderbilt.isis.chariot.datatypes.DatatypesPackage.Literals.*
/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DatatypesValidator extends AbstractDatatypesValidator {
	public static val ILLEGAL_TYPE = 'issue.illegalType'
	@Inject extension AllowableTypes allowableTypes
	@Check
	def checkDataTypesDefined(MessageElement greeting) {
		if(greeting.type!=null){
			if(!greeting.type.isMongoType){
				error('Only certain types are allowed.Please see documentation.', MESSAGE_ELEMENT__TYPE, ILLEGAL_TYPE)
			} 
		}
	}
	
	@Check
	def checkArrayDeclaration(MessageElement greeting) {
		if(greeting.type!=null && greeting.isIsArray){
			if(!greeting.type.type.isMongoBean){
				error('We only support List of Message Declarations. Primitive type list is not supported.', MESSAGE_ELEMENT__TYPE, ILLEGAL_TYPE)
			} 
		}
	}
}
