/*
* generated by Xtext
*/
package edu.vanderbilt.isis.chariot;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ChariotStandaloneSetup extends ChariotStandaloneSetupGenerated{

	public static void doSetup() {
		new ChariotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

