/*
 * generated by Xtext
 */
package edu.vanderbilt.isis.chariot;

import org.eclipse.xtext.generator.IGenerator;

import edu.vanderbilt.isis.chariot.generator.ChariotGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ChariotRuntimeModule extends edu.vanderbilt.isis.chariot.AbstractChariotRuntimeModule {

	/**
	 * Avoids to use the default org.eclipse.xtext.xbase.compiler.JvmModelGenerator
	 * when using xbase.
	 * @see org.xtext.example.helloxbase.AbstractHelloXbaseRuntimeModule#bindIGenerator()
	 */
	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return ChariotGenerator.class;
	}

}
